# Generated by Django 4.2.25 on 2025-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_spb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spb_sap',
            options={'ordering': ['device', 'interface']},
        ),
        migrations.AddField(
            model_name='spb_sap',
            name='encapsulations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
