# Generated by Django 4.2.25 on 2025-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_spb', '0002_alter_spb_sap_options_spb_sap_encapsulations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spb_sap',
            name='encapsulations',
        ),
        migrations.AlterField(
            model_name='spb_sap',
            name='encapsulation',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
