# Generated by Django 4.2.25 on 2025-12-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_spb', '0003_remove_spb_sap_encapsulations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spb_sap',
            options={'ordering': ['device', 'interface'], 'verbose_name': 'SPB SAP', 'verbose_name_plural': 'SPB SAPs'},
        ),
    ]
