# Generated by Django 4.2.25 on 2025-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_spb', '0004_alter_spb_sap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spb_topology',
            name='topology_hello_interval',
            field=models.PositiveIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='spb_topology',
            name='topology_hello_multiplier',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='spb_topology',
            name='topology_interface_type',
            field=models.CharField(default='p2p', max_length=12),
        ),
        migrations.AlterField(
            model_name='spb_topology',
            name='topology_metric',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
    ]
