download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/networktocode-nautobot-5.16.0.tar.gz
format_version: 1.0.0
name: nautobot
namespace: networktocode
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.16.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/networktocode/nautobot/versions/5.16.0/
